#
# Module manifest for module 'CommonModules'
#
# Generated by: Debanjan Das
#
# Generated on: 7-26-2022
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule        = 'CommonModules.psm1'

    # Version number of this module.
    ModuleVersion     = '1.0.1'

    # ID used to uniquely identify this module
    GUID              = '36c96b5c-c4a2-4480-acad-4643078c84e3'

    # Author of this module
    Author            = 'Debanjan Das'

    # Company or vendor of this module
    CompanyName       = 'Not Applicable'

    # Copyright statement for this module
    Copyright         = 'Not Applicable'


    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '5.1'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules   = @(
        @{
            ModuleName    = 'Az.Accounts'
            ModuleVersion = '2.8.0'
        },
        @{
            ModuleName    = 'Az.Compute'
            ModuleVersion = '4.27.0'
        },
        @{
            ModuleName    = 'Az.Network'
            ModuleVersion = '4.17.0'
        },
        @{
            ModuleName    = 'Az.OperationalInsights'
            ModuleVersion = '3.1.0'
        },
        @{
            ModuleName    = 'Az.KeyVault'
            ModuleVersion = '4.5.0'
        },
        @{
            ModuleName    = 'Az.sql'
            ModuleVersion = '3.9.0'
        }    
    )



    # Functions to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no functions to export.
    FunctionsToExport = @(
        'New-ResourceGroup',
        'New-AzureAppGateway',
        'New-AzureKeyVault',
        'New-LAWorkSpace',
        'New-VMCreation',
        'New-LoadBalancerCreation',
        'New-OrModifyNetworkSecurityGrp',
        'New-SQLDatabase',
        'New-BackupConfiguration'
    )
    # this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no cmdlets to export.
    # CmdletsToExport   = '*'

    # Variables to export from this module
    # VariablesToExport = '*'

    # Aliases to export from this module, for best performance, do not use wildcards and do not delete the entry, use an empty array if there are no aliases to export.
    # AliasesToExport   = @()


    # Private data to pass to the module specified in RootModule/ModuleToProcess. This may also contain a PSData hashtable with additional module metadata used by PowerShell.
    PrivateData       = @{

        PSData = @{

            # Tags applied to this module. These help with module discovery in online galleries.
            # Tags = @()

            # A URL to the license for this module.
            # LicenseUri = ''

            # A URL to the main website for this project.
            # ProjectUri = ''

            # A URL to an icon representing this module.
            # IconUri = ''

            # ReleaseNotes of this module
            # ReleaseNotes = ''

        } # End of PSData hashtable

    } # End of PrivateData hashtable


}
